# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd" "amdgpu"];
  services.upower.enable = true;
  boot.loader.grub.splashImage = ./../../background.jpg;
  boot.kernelPackages = pkgs.linuxPackages_latest;
  hardware.xpadneo.enable = true;
  hardware.xone.enable = true;
  services.udev.packages = [pkgs.game-devices-udev-rules];
  boot.kernelParams = [
    "usbcore.autosuspend=-1"
  ];
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
  };
  zramSwap.enable = true;
  zramSwap.priority = 100; # Highest priority
  zramSwap.memoryPercent = 50; # Uses up to 8GB of RAM for compression
  swapDevices = [
    {device = "/dev/disk/by-uuid/3a0d3bbd-adce-48e8-ab46-dc0083044b2b";}
    {
      device = "/var/lib/swapfile";
      size = 16384;
      priority = 5;
    }
  ];
  boot.kernel.sysctl = {
    # Don't swap aggressively; stay in RAM/zRam as long as possible
    "vm.swappiness" = 10;
    # Improve file system cache pressure
    "vm.vfs_cache_pressure" = 50;
  };
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.systemd-boot.enable = true;
  services.xserver.videoDrivers = ["amdgpu"];
  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  services.udev.extraRules = ''
    # wierd xpad fix
    SUBSYSTEM=="usb", ATTR{idVendor}=="2dc8", ATTR{idProduct}=="6013", MODE="0660", GROUP="users"
        KERNEL=="ttyACM0", MODE="0777"
  '';
}
